Question 1

In [2]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=arr.reshape(2, 5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Question 2

In [14]:
arr=np.arange(1,21)
data=arr[5:15]
data

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Question 3

In [17]:
import pandas as pd

In [21]:
data={'apples': 3, 'bananas': 2, 'oranges': 1}
series=pd.Series(data)
series["Pears"]=4

Question 4

In [28]:
data={
    "Name":['ab1','ab2','ab3','ab4','ab5','ab6','ab7','ab8','ab9','ab10'],
    "Roll No":[1,2,3,4,5,6,7,8,9,10],
    "Division":['A','C','B','C','A','B','C','C','B','C']}
df=pd.DataFrame(data)
df

Name  Roll No Division
0   ab1        1        A
1   ab2        2        C
2   ab3        3        B
3   ab4        4        C
4   ab5        5        A
5   ab6        6        B
6   ab7        7        C
7   ab8        8        C
8   ab9        9        B
9  ab10       10        C

Question 5

In [31]:
occupation=['Programmer','Manager','Analyst','Manager','Analyst','Programmer','Programmer','Analyst','Manager','Programmer']
df["occupation"]=occupation
df

Name  Roll No Division  occupation
0   ab1        1        A  Programmer
1   ab2        2        C     Manager
2   ab3        3        B     Analyst
3   ab4        4        C     Manager
4   ab5        5        A     Analyst
5   ab6        6        B  Programmer
6   ab7        7        C  Programmer
7   ab8        8        C     Analyst
8   ab9        9        B     Manager
9  ab10       10        C  Programmer

Question 6

In [34]:
df.loc[df["Roll No"]>8]

Name  Roll No Division  occupation
8   ab9        9        B     Manager
9  ab10       10        C  Programmer

Question 7

In [37]:
df.to_csv("assignment_1.csv")

In [41]:
data=pd.read_csv("assignment_1.csv")
data

Unnamed: 0  Name  Roll No Division  occupation
0           0   ab1        1        A  Programmer
1           1   ab2        2        C     Manager
2           2   ab3        3        B     Analyst
3           3   ab4        4        C     Manager
4           4   ab5        5        A     Analyst
5           5   ab6        6        B  Programmer
6           6   ab7        7        C  Programmer
7           7   ab8        8        C     Analyst
8           8   ab9        9        B     Manager
9           9  ab10       10        C  Programmer